name: surat_masuk_keluar_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.1
  smooth_page_indicator: ^1.2.0+3
  google_nav_bar: ^5.0.7
  intl: ^0.20.2
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/assets/
